### ISSUE TITLE
update category

### ISSUE THREAD

**Issue by mangweb** [bellthomas/Wordpress_PostController#1]
can we add a function to update categories as well?

**Comment by bellthomas** [comment]
PostController already has a function to update categories, but I had accidentally left the usage notes out of the readme file (Thanks for pointing this out!).

You can find the updated section on add_category() here;
https://github.com/HarriBellThomas/Wordpress_PostController#categories

**Comment by mangweb** [comment]
be good if theres an example in the readme on how to rename 'Uncategorized" category to something else.

**Comment by bellthomas** [comment]
This isn't really related to post management (categories is a taxonomy) - good idea though. Perhaps I'll have a look at how to do this (I may even write a tutorial - no promises though!)
